# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab69f7c4e5ed6b8b91faae6864c3279812f9cb8a300a0d237d964aff9ba6c78d44f87e0abbf22c184881db1a8d13ce154d060f9f7d09e7cc678eda7df4582960

test:
  secret_key_base: f33c3ad5e118672f504b4b96b48192a2123cbb351fd5f6a5308cdeb136e2e7377d9d69edafb3e4c9eee7f14401df96a786eeb9020789e373f9c6fffddaaf769e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
